### PR TITLE
[CSH-5] creating user session information sign up info in database

### PR DESCRIPTION
**Pull request by MuhammedAdelTaha**
Hi all, this is a request for merging 💯

### CODE REVIEW

**Review by Ali-Mones — CHANGES_REQUESTED** [review]
Please remove the .idea folder and remove the Milestone-1 folder taking its content outside

**Review by MarwanElsays — APPROVED** [review]
nice job

**Review by MuhammedAdelTaha — COMMENTED** [review]
Thank you for your feedback 😘✌️

**Comment by MuhammedAdelTaha** [comment]
> Please remove the .idea folder and remove the Milestone-1 folder taking its content outside

**Review by MuhammedAdelTaha — COMMENTED** [review]
Thank you for you feedback

**Pull request merged**
